# .github/workflows/quotes.yml
name: Update Bullion Quotes
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kuala_Lumpur
      TARGET_URL: ${{ secrets.BULLION_TARGET_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i
      - run: npx playwright install --with-deps
      - name: Run scraper with fallbacks
        run: |
          BROWSER=firefox  node scraper.js || \
          BROWSER=webkit   node scraper.js || \
          BROWSER=chromium node scraper.js
      - name: Commit & push JSON
        if: success()
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@example.com"
          git add data/quotes.json
          git commit -m "Update quotes [skip ci]" || echo "No changes"
          git push
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            debug/page.png
            debug/content.html
            debug/network.json
            debug/rows.json
          if-no-files-found: warn
